version: "3.8"
services:
  postgres:
    container_name: bd-postgres-fonbec
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: p6o
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5431:5432"
  pgadmin:
    container_name: pgadmin-postgres-fonbec
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: molinamauro12@gmail.com # cambiar
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "5050:80"
